/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bbdd;

import java.awt.event.ItemListener;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Yosep
 */
public class BBDDInformation extends javax.swing.JFrame {

    
    
    public Connection connection;
    String user;
    Statement st;
    PreparedStatement ps;
    CallableStatement cs;
    ResultSet rs;
    ResultSet rst;
    DatabaseMetaData metadata;
    ResultSetMetaData rsmetadata;
    private DefaultTableModel columna;
    private DefaultTableModel campo;
    String camposAcumulados;
    
    
    public BBDDInformation(Connection connection, String usuario) throws SQLException {
        
        initComponents();        
        this.connection = connection;
        this.user = usuario;
        columna = (DefaultTableModel) columnasTB.getModel();
        campo = (DefaultTableModel) camposTB.getModel();
        generarTablas();
        //generarColumnas();
    }

    private BBDDInformation() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     *
     */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tablasCB = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        columnasTB = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        camposTB = new javax.swing.JTable();
        seleccionarBT = new javax.swing.JButton();
        borrarBT = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        columnasCB = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        operadorCB = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        valorTF = new javax.swing.JTextField();
        EjecutarTF = new javax.swing.JTextField();
        ejecutarBT = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        consultaTB = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(580, 850));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel1.setText("TABLA");

        tablasCB.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        tablasCB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tablasCBFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tablasCBFocusLost(evt);
            }
        });
        tablasCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablasCBActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel2.setText("COLUMNA");

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel3.setText("CAMPOS SELECCIONADOS");

        columnasTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Campos"
            }
        ));
        jScrollPane1.setViewportView(columnasTB);

        camposTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Campos seleccionados"
            }
        ));
        jScrollPane2.setViewportView(camposTB);

        seleccionarBT.setText(">");
        seleccionarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarBTActionPerformed(evt);
            }
        });

        borrarBT.setText("<");
        borrarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarBTActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel4.setText("FILTRAR");

        columnasCB.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        columnasCB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                columnasCBFocusGained(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel5.setText("OPERADOR");

        operadorCB.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel6.setText("VALOR");

        valorTF.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        valorTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                valorTFFocusLost(evt);
            }
        });

        ejecutarBT.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        ejecutarBT.setText("EJECUTAR");

        consultaTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(consultaTB);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(columnasCB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(operadorCB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(99, 99, 99)
                                        .addComponent(valorTF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(99, 99, 99)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EjecutarTF, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ejecutarBT)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tablasCB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(seleccionarBT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(borrarBT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(82, 82, 82)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tablasCB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(seleccionarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(borrarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(columnasCB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(operadorCB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorTF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EjecutarTF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ejecutarBT))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablasCBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tablasCBFocusLost
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_tablasCBFocusLost

    private void tablasCBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tablasCBFocusGained
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_tablasCBFocusGained

    private void columnasCBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_columnasCBFocusGained
        // TODO add your handling code here:
        
        generarOperadores();
        
    }//GEN-LAST:event_columnasCBFocusGained

    private void tablasCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablasCBActionPerformed
        // TODO add your handling code here:
        
        generarColumnasTB();
        
    }//GEN-LAST:event_tablasCBActionPerformed

    private void seleccionarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarBTActionPerformed
        // TODO add your handling code here:
        
        //int selectedColumn = camposTB.getSelectedColumn();
        int selectedRow = columnasTB.getSelectedRow();
        
        //Si existe una fila seleccionada enonces:
        if(selectedRow>=0){
            
            String datosFila[]=new String[1];
            
            datosFila[0]=columna.getValueAt(selectedRow, 0).toString();
           
            campo.addRow(datosFila);
            columnasCB.addItem(datosFila[0]);
            columna.removeRow(selectedRow);
        }
        
        //campo.setValueAt(campo, selectedRow, selectedColumn);
        
        
    }//GEN-LAST:event_seleccionarBTActionPerformed

    private void valorTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorTFFocusLost
        // TODO add your handling code here:
        
        String tablaActual = tablasCB.getSelectedItem().toString();
        String filtroActual = columnasCB.getSelectedItem().toString();
        String operadorActual = operadorCB.getSelectedItem().toString();
        String valor = valorTF.getText();
        
        EjecutarTF.setText("SELECT " + camposSQL() + " FROM " + tablaActual + " WHERE " + filtroActual + " " + operadorActual + " " + valor);
    }//GEN-LAST:event_valorTFFocusLost

    public String camposSQL(){
        
        for (int i = 0; i < campo.getRowCount(); i++) {
        
            camposAcumulados = camposTB.getValueAt(i, 0).toString();
            
            
            if(camposAcumulados.equals(camposAcumulados))
            
                camposAcumulados = camposAcumulados;
            
            else if(!camposAcumulados.equals(camposAcumulados)){
                
                camposAcumulados += camposAcumulados;
                
                
            }
        }
        
        /*String camposAcumulados = datosFila[0];
        camposAcumulados += camposAcumulados;*/
        
        return camposAcumulados;
        
    }
    
    private void borrarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarBTActionPerformed
        // TODO add your handling code here:
        
        //int selectedColumn = camposTB.getSelectedColumn();
        int selectedRow = camposTB.getSelectedRow();
       
        //Si existe una fila seleccionada enonces:
        if(selectedRow>=0){
            
            String datosFila[]=new String[1];
            
            datosFila[0]=campo.getValueAt(selectedRow, 0).toString();
            
            columna.addRow(datosFila);
            columnasCB.removeItem(datosFila[0]);
            campo.removeRow(selectedRow);  
        }
        
    }//GEN-LAST:event_borrarBTActionPerformed

    
    
    
    public void generarTablas(){

        tablasCB.removeAllItems();
        
        try {
            /*metadata = connection.getMetaData();
            // establecer sentencia
            st = connection.createStatement();
            // recoger los datos de la consulta SQL
            rs = st.executeQuery("SELECT TABLE_NAME FROM ALL_TABLES WHERE OWNER LIKE '"+user+"'");
            // recoger la estructura del ResultSet anterior
            
            while(rs.next()){
                
                tablasCB.addItem(rs.getString(1));
                
            }*/
            
            metadata = connection.getMetaData();
            user = metadata.getUserName().toUpperCase();
            rs = metadata.getTables(null,user, "%", new String[]{"TABLE"}); //  metadata.getSchemas().toString().toUpperCase()
            
            while(rs.next()){
                
                tablasCB.addItem(rs.getString("TABLE_NAME"));
                
            }
            //new String[]{"TABLE"}*/
            
            rs.close();
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
    }
    
    
    public void generarColumnasTB(){
        
        columna.setRowCount(0);
        
        String tabla = tablasCB.getSelectedItem().toString();
        
            try {
            
            metadata = connection.getMetaData();
            user = metadata.getUserName().toUpperCase();
            rst = metadata.getColumns(null,user,tabla,"%"); //  metadata.getSchemas().toString().toUpperCase()
            
            while(rst.next()){
                
                columna.addRow(new Object[]{rst.getString("COLUMN_NAME")});               
            }
            
            
            rst.close();     
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
 
    }
    
    /*public void generarColumnasCB(){
        
        columnasCB.removeAllItems();
        
        String tabla = tablasCB.getSelectedItem().toString();

            try {
            
            metadata = connection.getMetaData();
            user = metadata.getUserName().toUpperCase();
            rs = metadata.getColumns(null,user,tabla,"%"); //  metadata.getSchemas().toString().toUpperCase()
            
            while(rs.next()){
                
                columnasCB.addItem(rs.getString("COLUMN_NAME"));
                           
            }
            //new String[]{"TABLE"}
            
            rs.close();     
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
 
    }*/
    
    
    public void generarOperadores(){
        
        operadorCB.removeAllItems();
        
        String tabla = tablasCB.getSelectedItem().toString();
        String columna = columnasCB.getSelectedItem().toString();

            try {
            
            metadata = connection.getMetaData();
            user = metadata.getUserName().toUpperCase();
            rs = metadata.getColumns(null,user,tabla,columna); //  metadata.getSchemas().toString().toUpperCase()
            
            while(rs.next()){
                
                //System.out.println(rs.getString("TYPE_NAME"));
                
                if(rs.getString("TYPE_NAME").equals("VARCHAR2")){

                    operadorCB.setEnabled(true);
                    operadorCB.addItem("LIKE");
                    operadorCB.addItem("=");

                }else if(rs.getString("TYPE_NAME").equals("NUMBER") || rs.getString("TYPE_NAME").equals("DATE")){

                    operadorCB.setEnabled(true);
                    operadorCB.addItem(">");
                    operadorCB.addItem("<");
                    operadorCB.addItem(">=");
                    operadorCB.addItem("<=");
                    operadorCB.addItem("=");
                    
                }else if(columnasCB.getItemCount() == 0){
                    
                    columnasCB.setEnabled(false);
                    
                }       
            }

            //new String[]{"TABLE"}
            
            rs.close();     
            
        } catch (SQLException ex) {
            Logger.getLogger(BBDDInformation.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BBDDInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BBDDInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BBDDInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BBDDInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fotablasCB   /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BBDDInformation().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EjecutarTF;
    private javax.swing.JButton borrarBT;
    private javax.swing.JTable camposTB;
    private javax.swing.JComboBox<String> columnasCB;
    private javax.swing.JTable columnasTB;
    private javax.swing.JTable consultaTB;
    private javax.swing.JButton ejecutarBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> operadorCB;
    private javax.swing.JButton seleccionarBT;
    private javax.swing.JComboBox<String> tablasCB;
    private javax.swing.JTextField valorTF;
    // End of variables declaration//GEN-END:variables

   
}
